//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 05:23:19 PM MSK 
//


package com.techprimers.spring_boot_soap_example;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userWithRoles" type="{http://techprimers.com/spring-boot-soap-example}userWithRoles"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userWithRoles"
})
@XmlRootElement(name = "getUserWithRolesResponse")
public class GetUserWithRolesResponse {

    @XmlElement(required = true)
    protected UserWithRoles userWithRoles;

    /**
     * Gets the value of the userWithRoles property.
     * 
     * @return
     *     possible object is
     *     {@link UserWithRoles }
     *     
     */
    public UserWithRoles getUserWithRoles() {
        return userWithRoles;
    }

    /**
     * Sets the value of the userWithRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserWithRoles }
     *     
     */
    public void setUserWithRoles(UserWithRoles value) {
        this.userWithRoles = value;
    }

}
