//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 05:23:19 PM MSK 
//


package com.techprimers.spring_boot_soap_example;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.techprimers.spring_boot_soap_example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetUserRequest_QNAME = new QName("http://techprimers.com/spring-boot-soap-example", "getUserRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.techprimers.spring_boot_soap_example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link DeleteUserWithRolesRequest }
     * 
     */
    public DeleteUserWithRolesRequest createDeleteUserWithRolesRequest() {
        return new DeleteUserWithRolesRequest();
    }

    /**
     * Create an instance of {@link AddUserWithRolesRequest }
     * 
     */
    public AddUserWithRolesRequest createAddUserWithRolesRequest() {
        return new AddUserWithRolesRequest();
    }

    /**
     * Create an instance of {@link UserWithRoles }
     * 
     */
    public UserWithRoles createUserWithRoles() {
        return new UserWithRoles();
    }

    /**
     * Create an instance of {@link GetValidationResponse }
     * 
     */
    public GetValidationResponse createGetValidationResponse() {
        return new GetValidationResponse();
    }

    /**
     * Create an instance of {@link UpdateUserWithRolesRequest }
     * 
     */
    public UpdateUserWithRolesRequest createUpdateUserWithRolesRequest() {
        return new UpdateUserWithRolesRequest();
    }

    /**
     * Create an instance of {@link GetUserWithRolesResponse }
     * 
     */
    public GetUserWithRolesResponse createGetUserWithRolesResponse() {
        return new GetUserWithRolesResponse();
    }

    /**
     * Create an instance of {@link GetUserWithRolesRequest }
     * 
     */
    public GetUserWithRolesRequest createGetUserWithRolesRequest() {
        return new GetUserWithRolesRequest();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://techprimers.com/spring-boot-soap-example", name = "getUserRequest")
    public JAXBElement<Object> createGetUserRequest(Object value) {
        return new JAXBElement<Object>(_GetUserRequest_QNAME, Object.class, null, value);
    }

}
